theme = "nord-dark"
icons = "awesome"

[[block]]
block = "bluetooth"
mac = "4C:87:5D:7D:D5:C4"
format = "Nightshade"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
icons_format = "{icon}"
format = "{utilization:3} {barchart} {frequency}"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength}"
interval = 5
hide_inactive = true
hide_missing = true

[[block]]
block = "backlight"

[[block]]
block = "sound"
driver = "pulseaudio"
natural_mapping = true
show_volume_when_muted = true
on_click = "pactl set-sink-mute @DEFAULT_SINK@ toggle"

[[block]]
block = "sound"
driver = "pulseaudio"
natural_mapping = true
show_volume_when_muted = true
on_click = "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
device_kind = "source"

[[block]]
block = "time"
interval = 20
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 20
allow_missing = true
hide_missing = true
format = "{percentage} {time}"
